name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Create Artifact Registry repository if not exists
      run: |
        gcloud artifacts repositories describe my-test-weather-app --location=${{ secrets.GCP_REGION }} || \
        gcloud artifacts repositories create my-test-weather-app --repository-format=docker --location=${{ secrets.GCP_REGION }}

    - name: Build Docker image
      run: |
        IMAGE_NAME=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-test-weather-app/weather-gui-app
        docker build -t $IMAGE_NAME .

    - name: Push Docker image to Artifact Registry
      run: |
        IMAGE_NAME=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-test-weather-app/weather-gui-app
        docker push $IMAGE_NAME

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy weather-gui-app \
          --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-test-weather-app/weather-gui-app \
          --region=${{ secrets.GCP_REGION }} \
          --platform=managed \
          --allow-unauthenticated \
          --update-env-vars=OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}