name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev

    - name: Build Docker image
      run: |
        IMAGE_NAME=${GCP_REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-test-weather-app/weather-gui-app
        docker build -t $IMAGE_NAME .

    - name: Push Docker image to Artifact Registry
      run: |
        IMAGE_NAME=${GCP_REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-test-weather-app/weather-gui-app
        docker push $IMAGE_NAME

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy weather-gui-app \
          --image ${GCP_REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-test-weather-app/weather-gui-app \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --port 3001

    - name: Post-deployment cleanup
      run: docker image prune -f