name: GAE Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Post-deployment verification
      run: curl -f https://${{ secrets.GCP_PROJECT_ID }}.appspot.com/health